name: Test-Build-Deploy
on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['14', '16']
        os: [ubuntu-latest]

    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm test
    
  build_and_deploy:
    needs: test
    name: Build and Deploy to Github Pages
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: npm build
      run: |
        npm install --production
        npm run build --if-present
    
    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v1.0.7
      with:
        # Path of the directory containing the static assets.
        path: build
          
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.3
