on:
  push:
    branches:
    - main
    - release/*

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest]

    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
    
  build_and_deploy:
    name: Build and Deploy to Github Pages
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ node_version }}

    - name: npm build
      run: |
        npm install
        npm run build --if-present
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: |
          build/**
          
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.3
